const puppeteer = require("puppeteer");

/**
 * Generic PDF generator.
 * @param {Object} data
 * @param {string} data.title
 * @param {string} [data.subtitle]
 * @param {string} [data.businessName]
 * @param {Array}  data.sections - [{ heading, content, table?: { headers, rows } }]
 * @returns {Buffer}
 */
async function genericToPdf({ title = "Report", subtitle = "", businessName = "", sections = [] }) {
  const sectionsHtml = sections.map((sec) => {
    let html = `<div class="section">`;
    if (sec.heading) html += `<h2 class="section-title">${esc(sec.heading)}</h2>`;
    if (sec.content) html += `<p class="section-text">${esc(sec.content).replace(/\n/g, "<br>")}</p>`;

    if (sec.table?.headers?.length) {
      html += `<table><thead><tr>${sec.table.headers.map((h) => `<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>`;
      (sec.table.rows || []).forEach((row, i) => {
        html += `<tr class="${i % 2 === 1 ? "alt" : ""}">${row.map((cell) => `<td>${esc(String(cell ?? ""))}</td>`).join("")}</tr>`;
      });
      html += `</tbody></table>`;
    }

    html += `</div>`;
    return html;
  }).join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background:#fff; color:#0F172A; padding:48px; }
    .header { border-bottom:2px solid #E2E8F0; padding-bottom:20px; margin-bottom:32px; display:flex; justify-content:space-between; align-items:flex-end; }
    .header-left h1 { font-size:26px; font-weight:800; color:#0F172A; }
    .header-left p { font-size:13px; color:#64748B; margin-top:4px; }
    .header-right { font-size:12px; color:#94A3B8; text-align:right; }
    .section { margin-bottom:32px; }
    .section-title { font-size:15px; font-weight:700; color:#1D4ED8; border-bottom:1px solid #DBEAFE; padding-bottom:6px; margin-bottom:14px; }
    .section-text { font-size:13px; color:#334155; line-height:1.7; margin-bottom:12px; }
    table { width:100%; border-collapse:collapse; margin-top:8px; }
    th { background:#1D4ED8; color:#fff; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:0.5px; padding:10px 12px; text-align:left; }
    td { padding:10px 12px; font-size:13px; color:#334155; border-bottom:1px solid #F1F5F9; }
    tr.alt td { background:#F8FAFC; }
    .footer { margin-top:40px; padding-top:14px; border-top:1px solid #E2E8F0; display:flex; justify-content:space-between; }
    .footer p { font-size:11px; color:#94A3B8; }
  </style>
</head>
<body>
  <div class="header">
    <div class="header-left">
      <h1>${esc(title)}</h1>
      ${subtitle ? `<p>${esc(subtitle)}</p>` : ""}
      ${businessName ? `<p>${esc(businessName)}</p>` : ""}
    </div>
    <div class="header-right">${new Date().toLocaleDateString()}</div>
  </div>
  ${sectionsHtml}
  <div class="footer">
    <p>Maggo — Business Management</p>
    <p>Generated by AI Assistant</p>
  </div>
</body>
</html>`;

  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage", "--single-process", "--no-zygote"],
  });
  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: "networkidle0" });
  const buf = await page.pdf({ format: "A4", printBackground: true });
  await browser.close();
  return buf;
}

function esc(str) {
  return String(str || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

module.exports = { genericToPdf };
